

"""create users table

Revision ID: b7718604ad46
Revises: 
Create Date: 2026-08-16 12:29:47.612955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7718604ad46'
down_revision = None
branch_labels = None
depends_on = None



    
def upgrade() -> None:
    op.create_table(
    'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('fullname', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###